### ISSUE TITLE
v3.4.2: manifest file is failing LAMS checks

### ISSUE THREAD

**Issue by wsjk** [looker-open-source/look-at-me-sideways#209]
Since v3.4.2, our Github Actions running LAMS have been failing custom LAMS rules for manifest file. It seems like a formatting error failing because of the custom rules we are defining in the manifest file?

Here's the lookml in our manifest file where we define LAMS rules

```
#LAMS
#rule: K3{} # Primary keys first
#rule: K4{} # Primary keys hidden
#rule: E1{} # Join with subst'n operator
#rule: E2{} # Join on PK for "one" joins
#rule: E6{} # FK joins are m:1
#rule: E7{} # Explore label 25-char max
#rule: T1{} # Triggers use datagroups
#rule: T2{} # Primary keys in DT
#rule: W1{} # Block indentation
#rule: K7{} # Provide one `primary_key`
#rule: explore_source {
#  description: "Derived table must use explore_source"
#  match: "$.*.*.view[?(@.derived_table)]"
#  expr_rule: (=== ::match:derived_table:sql undefined);;
#}
#rule: no_sql_in_dimensions {
#  description: "no sql in dimensions"
#  match: "$.*.*.view.[dimension].*"
#  expr_rule: ($let myvar ($boolean ($match ".*SELECT.*FROM" ::match:sql))) (=== myvar false) ;;
#}
#rule: no_sql_in_measures {
#  description: "no sql in measures"
#  match: "$.*.*.view.[measure].*"
#  expr_rule: ($let myvar ($boolean ($match ".*SELECT.*FROM" ::match:sql))) (=== myvar false) ;;
#}
#rule: no_vw_in_filename {
#  description: "remove 'vw_' from filenames"
#  match: "$.file[*]"
#  expr_rule:
#  ($if
#    ($all
#      (=== ::match:$file_type "view")
#      (
#         $boolean (
#            $match
#            "^vw_"
#            ::match:$file_name
#         )
#      )
#    )
#      ($concat "View file here "  ::match:$file_name)
#      true
#  )
#  ;;
#}
#rule: no_vw_in_view_name {
#  description: "Remove 'vw_' from view names"
#  match: "$.file.*.view.*"
#  expr_rule:
#  ($if
#    ($all
#      (=== ::match:$type "view")
#      (
#         $boolean (
#            $match
#            "^vw_"
#            ::match:$name
#         )
#      )
#    )
#      ($concat "Views should not have 'vw_' in name "  ::match:$name)
#      true
#  )
#  ;;
#}
```

![image](https://github.com/user-attachments/assets/95dfbe39-1c14-40d1-bea1-b1d9db6ba450)

**Comment by fabio-looker** [comment]
Hi @wsjk - sorry about that! Since v3.3, there was already a reported issue with whitespace handling and conditional comments. It was a tricky situation to resolve without requiring some users to change their whitespace and I incorrectly assumed anyone who was going to be affected by the issue had already been broken by it, and I tried to make the resolution a patch change :-/ 

I think what I will do today is revert that patch in a new patch (v3.4.3) today so that the whitespace handling as of v3.4.1 remains, but republish this as v4. Going forward, the whitespace handling around comments will be to preserve whitespace before the comment and consume up to one space character after the #, similar to how auto-commenting works in the Looker IDE with the Ctrl+/ command.

**Comment by fabio-looker** [comment]
v3.4.3 is live on NPM and reverts the whitespace handling to that of v3.4.1. Hope the interruption is now resolved for you.

**Comment by wsjk** [comment]
So i tried the auto commenting shortcut for the whitespace issue and still getting lams errors

```
# LAMS
# rule: K3{} # Primary keys first
# rule: K4{} # Primary keys hidden
# rule: E1{} # Join with subst'n operator
# rule: E2{} # Join on PK for "one" joins
# rule: E6{} # FK joins are m:1
# rule: E7{} # Explore label 25-char max
# rule: T1{} # Triggers use datagroups
# rule: T2{} # Primary keys in DT
# rule: W1{} # Block indentation
# rule: W1{} # Block indentation
# rule: K7{} # Provide one `primary_key`
# rule: F4{} # Description or hidden
# rule: ES1 {
#   description: "Derived table must use explore_source"
#   match: "$.*.*.view[?(@.derived_table)]"
#   expr_rule: (=== ::match:derived_table:sql undefined);;
# }
# rule: no_sql_in_dimensions {
#   description: "no sql in dimensions"
#   match: "$.*.*.view.[dimension].*"
#   expr_rule: ($let myvar ($boolean ($match ".*SELECT.*FROM" ::match:sql))) (=== myvar false) ;;
# }
# rule: no_sql_in_measures {
#   description: "no sql in measures"
#   match: "$.*.*.view.[measure].*"
#   expr_rule: ($let myvar ($boolean ($match ".*SELECT.*FROM" ::match:sql))) (=== myvar false) ;;
# }
# rule: no_vw_in_filename {
#   description: "remove 'vw_' from filenames"
#   match: "$.file[*]"
#   expr_rule:
#   ($if
#     ($all
#       (=== ::match:$file_type "view")
#       (
#         $boolean (
#             $match
#             "^vw_"
#             ::match:$file_name
#         )
#       )
#     )
#       ($concat "View file here "  ::match:$file_name)
#       true
#   )
#   ;;
# }
# rule: no_vw_in_view_name {
#   description: "Remove 'vw_' from view names"
#   match: "$.file.*.view.*"
#   expr_rule:
#   ($if
#     ($all
#       (=== ::match:$type "view")
#       (
#         $boolean (
#             $match
#             "^vw_"
#             ::match:$name
#         )
#       )
#     )
#       ($concat "Views should not have 'vw_' in name "  ::match:$name)
#       true
#   )
#   ;;
# }
```

**Comment by wsjk** [comment]
it's also odd that i don't get same errors when running lams locally but only in GHA

**Comment by fabio-looker** [comment]
Can you confirm which version of LAMS you ran, as your run may have been after I already published v3.4.3?

**Comment by wsjk** [comment]
yea it's still 3.4.2 but i was trying to make it work for 3.4.2. But the only issue with 3.4.2 was only whitespace handling and my change should've worked right?

**Comment by fabio-looker** [comment]
Yes, the only change from 3.4.1 -> 3.4.2 -> 3.4.3 was how whitespace is passed through during the parser's conditional comment pre-processing.

The error makes it seem like W1 expects indentation before the `}`, which seems strange to me. If I'm being very honest, I don't actually use rule W1, and just implemented it as an example of whitespace handling, but if you have a repro for this secondary issue, I'd like to get it working consistently of course

**Comment by wsjk** [comment]
ok so I got lams to run for 3.4.2 if i remove whitespace before first line of custom rule and the closing bracket. 

For some reason, the whitespace handling for custom rules isn't working in the same way.

Have tested this in v4.0.0 and it works there as well.

```
#rule: ES1 {
#   description: "Derived table must use explore_source"
#   match: "$.*.*.view[?(@.derived_table)]"
#   expr_rule: (=== ::match:derived_table:sql undefined);;
#}
#rule: no_sql_in_dimensions {
#   description: "no sql in dimensions"
#   match: "$.*.*.view.[dimension].*"
#   expr_rule: ($let myvar ($boolean ($match ".*SELECT.*FROM" ::match:sql))) (=== myvar false) ;;
#}
#rule: no_sql_in_measures {
#   description: "no sql in measures"
#   match: "$.*.*.view.[measure].*"
#   expr_rule: ($let myvar ($boolean ($match ".*SELECT.*FROM" ::match:sql))) (=== myvar false) ;;
#}
#rule: no_vw_in_filename {
#   description: "remove 'vw_' from filenames"
#   match: "$.file[*]"
#   expr_rule:
#   ($if
#   ($all
#   (=== ::match:$file_type "view")
#   (
#   $boolean (
#   $match
#   "^vw_"
#   ::match:$file_name
#   )
#   )
#   )
#   ($concat "View file here "  ::match:$file_name)
#   true
#   )
#   ;;
#}
#rule: no_vw_in_view_name {
#   description: "Remove 'vw_' from view names"
#   match: "$.file.*.view.*"
#   expr_rule:
#   ($if
#   ($all
#   (=== ::match:$type "view")
#   (
#   $boolean (
#   $match
#   "^vw_"
#   ::match:$name
#   )
#   )
#   )
#   ($concat "Views should not have 'vw_' in name "  ::match:$name)
#   true
#   )
#   ;;
#}
```
